# Generated by Django 6.1.1 on 2026-09-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='seconds_per_question',
            field=models.PositiveIntegerField(default=20, help_text='Temps alloué à chaque question (ex. 20 s)', verbose_name='Secondes par question'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.PositiveIntegerField(default=30, help_text='Durée maximale globale en minutes', verbose_name='Durée totale (minutes)'),
        ),
    ]
