# Generated by Django 6.1.1 on 2026-09-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_seconds_per_question_alter_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Indice'),
        ),
    ]
