# Generated by Django 6.1.1 on 2026-09-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_question_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='teacher_comment',
            field=models.TextField(blank=True, verbose_name='Commentaire du professeur'),
        ),
    ]
