# Generated by Django 6.1.1 on 2026-10-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_quiz_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Notions et types de questions à privilégier lors de la génération IA.', verbose_name='Description du quiz'),
        ),
    ]
