# Generated by Django 6.1.1 on 2026-10-07 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_lesson_faq_lesson_summary'),
        ('quizzes', '0007_quiz_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizGenerationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_question_history', to='education.lesson')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lesson', 'signature'), name='unique_generated_question_per_lesson')],
            },
        ),
    ]
