"""
Programme officiel de mathématiques — EduBac.
"""

# Niveaux affichés pour l'élève (cartes cliquables)
STUDENT_LEVELS = [
    {
        'code': 'tronc_commun_lettres',
        'label': 'Tronc Commun Lettres',
        'icon': '📖',
        'color': 'lc-1',
        'maps_to': 'tronc_commun',  # contenu partagé si pas encore séparé
    },
    {
        'code': 'tronc_commun',
        'label': 'Tronc Commun Sciences',
        'icon': '🔬',
        'color': 'lc-2',
        'maps_to': 'tronc_commun',
    },
    {
        'code': '1ere_bac_sc',
        'label': 'Première Bac Sciences',
        'icon': '🧪',
        'color': 'lc-3',
        'maps_to': '1ere_bac_sc',
    },
    {
        'code': '1ere_bac_lettres',
        'label': 'Première Bac Lettres',
        'icon': '📝',
        'color': 'lc-4',
        'maps_to': '1ere_bac_lettres',
    },
    {
        'code': '1ere_bac_sm',
        'label': 'Première Bac Sciences Mathématiques',
        'icon': '∑',
        'color': 'lc-5',
        'maps_to': '1ere_bac_sm',
    },
    {
        'code': '2eme_bac_svt',
        'label': 'Deuxième Bac SVT',
        'icon': '🌿',
        'color': 'lc-6',
        'maps_to': '2eme_bac_svt',
    },
    {
        'code': '2eme_bac_pc',
        'label': 'Deuxième Bac PC',
        'icon': '⚛️',
        'color': 'lc-7',
        'maps_to': '2eme_bac_pc',
    },
    {
        'code': '2eme_bac_lettres',
        'label': 'Deuxième Bac Lettres',
        'icon': '📚',
        'color': 'lc-1',
        'maps_to': '2eme_bac_lettres',
    },
]

"""
Programme officiel de mathématiques — EduBac.
Structure prête pour associer un fichier (pdf) à chaque leçon plus tard.
"""

CURRICULUM = [
    {
        'code': 'tronc_commun',
        'label': 'Tronc Commun',
        'order': 1,
        'color': 'teal',
        'lessons': [
            'Les entiers naturels et notions d’arithmétique',
            'Les ensembles de nombres ℕ, ℤ, 𝔻, ℚ, ℝ',
            'L’ordre dans ℝ',
            'Les polynômes',
            'Équations, inéquations et systèmes',
            'Le calcul vectoriel dans le plan',
            'La projection dans le plan',
            'La droite dans le plan — géométrie analytique',
            'Bases de la trigonométrie',
            'Transformations usuelles dans le plan',
            'Équations et inéquations trigonométriques',
            'Le produit scalaire dans le plan',
            'Les fonctions numériques — généralités',
            'Géométrie dans l’espace',
            'Statistiques',
        ],
    },
    {
        'code': '1ere_bac_sc',
        'label': '1ère Bac Sciences',
        'order': 2,
        'color': 'green',
        'lessons': [
            'Notions de logique',
            'Généralités sur les fonctions numériques',
            'Le barycentre dans le plan',
            'Le produit scalaire dans le plan',
            'Les suites numériques',
            'Calcul trigonométrique',
            'La rotation dans le plan',
            'Les limites d’une fonction numérique',
            'La dérivation d’une fonction numérique',
            'Étude et représentation d’une fonction',
            'Vecteurs de l’espace',
            'Géométrie analytique de l’espace',
        ],
    },
    {
        'code': '1ere_bac_sm',
        'label': '1ère Bac Sciences Mathématiques',
        'order': 3,
        'color': 'purple',
        'lessons': [
            'Logique mathématique',
            'Ensembles et applications',
            'Généralités sur les fonctions numériques',
            'Le barycentre dans le plan',
            'Le produit scalaire dans le plan',
            'Calcul trigonométrique',
            'Les suites numériques',
            'Limites d’une fonction',
            'La rotation dans le plan',
            'La dérivation',
            'Étude des fonctions',
            'Vecteurs de l’espace',
            'Géométrie dans l’espace',
            'Dénombrement',
            'Le produit scalaire dans l’espace',
            'Arithmétique dans ℤ',
            'Le produit vectoriel',
        ],
    },
    {
        'code': '1ere_bac_lettres',
        'label': '1ère Bac Lettres',
        'order': 4,
        'color': 'cream',
        'lessons': [
            'Notions de logique',
            'Calcul numérique',
            'Généralités sur les fonctions',
            'Les suites numériques',
            'Les limites',
            'Dérivabilité',
            'Étude et représentation des fonctions',
            'Dénombrement',
        ],
    },
    {
        'code': '2eme_bac_svt',
        'label': '2ème Bac SVT',
        'order': 5,
        'color': 'green',
        'lessons': [
            'Limites et continuité',
            'Dérivation et étude des fonctions',
            'Suites numériques',
            'Fonctions primitives',
            'Fonctions logarithmiques',
            'Fonctions exponentielles',
            'Calcul intégral',
            'Équations différentielles',
            'Dénombrement et probabilités',
            'Nombres complexes — introduction',
        ],
    },
    {
        'code': '2eme_bac_pc',
        'label': '2ème Bac PC',
        'order': 6,
        'color': 'teal',
        'lessons': [
            'Limites et continuité',
            'Dérivation et étude des fonctions',
            'Suites numériques',
            'Fonctions primitives',
            'Fonctions logarithmiques',
            'Nombres complexes — Partie 1',
            'Fonctions exponentielles',
            'Nombres complexes — Partie 2',
            'Calcul intégral',
            'Équations différentielles',
            'Géométrie dans l’espace',
            'Dénombrement et probabilités',
        ],
    },
    {
        'code': '2eme_bac_lettres',
        'label': '2ème Bac Lettres',
        'order': 7,
        'color': 'purple',
        'lessons': [
            'Les suites numériques',
            'Dérivation et étude des fonctions',
            'Les fonctions logarithmes',
            'La fonction exponentielle népérienne',
            'Calcul de probabilités',
        ],
    },
]
