# Generated by Django 6.1.1 on 2026-09-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom de la classe')),
                ('code', models.CharField(blank=True, max_length=12, unique=True, verbose_name="Code d'invitation")),
                ('niveau', models.CharField(choices=[('tronc_commun', 'Tronc Commun'), ('1ere_bac_sc', '1ère Bac Sciences'), ('1ere_bac_sm', '1ère Bac Sciences Mathématiques'), ('1ere_bac_lettres', '1ère Bac Lettres'), ('2eme_bac_svt', '2ème Bac SVT'), ('2eme_bac_pc', '2ème Bac PC'), ('2eme_bac_lettres', '2ème Bac Lettres'), ('2eme_bac_sm', '2ème Bac Sciences Mathématiques')], max_length=50, verbose_name='Niveau')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant principal')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='classrooms.classroom', verbose_name='Classe')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Membre de classe',
                'verbose_name_plural': 'Membres de classe',
                'ordering': ['-joined_at'],
                'unique_together': {('classroom', 'user')},
            },
        ),
    ]
