# Generated by Django 6.1.1 on 2026-09-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
