# Generated by Django 6.1.2 on 2026-10-08 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_classroom_is_active'),
        ('whiteboard', '0002_quizcorrectionboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteboardShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='whiteboards/shares/%Y/%m/', verbose_name='Image')),
                ('title', models.CharField(default='Whiteboard', max_length=200, verbose_name='Titre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Partagé le')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_shares', to='classrooms.classroom', verbose_name='Classe')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboard_shares', to=settings.AUTH_USER_MODEL, verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Whiteboard partagé',
                'verbose_name_plural': 'Whiteboards partagés',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['classroom', '-created_at'], name='whiteboard__classro_e1d35f_idx')],
            },
        ),
    ]
