# Generated by Django 6.1.1 on 2026-09-27 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du cours')),
                ('niveau', models.CharField(choices=[('tronc_commun', 'Tronc Commun'), ('1ere_bac_sc', '1ère Bac Sciences'), ('1ere_bac_sm', '1ère Bac Sciences Mathématiques'), ('1ere_bac_lettres', '1ère Bac Lettres'), ('2eme_bac_svt', '2ème Bac SVT'), ('2eme_bac_pc', '2ème Bac PC'), ('2eme_bac_lettres', '2ème Bac Lettres'), ('2eme_bac_sm', '2ème Bac Sciences Mathématiques')], max_length=50, verbose_name='Niveau')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['niveau', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu pédagogique')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='lessons/pdfs/', verbose_name='Fichier PDF')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['course', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('file', models.FileField(upload_to='resources/', verbose_name='Fichier')),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('doc', 'Document')], default='pdf', max_length=20, verbose_name='Type')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='education.lesson', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
            },
        ),
    ]
