# Generated by Django 6.1.1 on 2026-09-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='faq',
            field=models.TextField(blank=True, verbose_name='FAQ (une question par ligne: Q?|R)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Fiche résumé'),
        ),
    ]
